### PR TITLE
Improved verbosity of exceptions 

### PR DESCRIPTION
**Pull request by kptLucek**
Basicly:
- Moved exceptions into their right namespace dir - **API CHANGE**,
- Added few dedicated exceptions,
- Made them nested - now just follow exception trace to find error which were almost impossible before,
- Improved error messages,

### CODE REVIEW

**Comment by asimlqt** [comment]
Thanks for taking the time to do this.

This is a huge commit, I'll merge it in the next major release.

**Comment by kptLucek** [comment]
Updated merge conflicts

**Comment by kptLucek** [comment]
WIP

**Comment by kptLucek** [comment]
@asimlqt

**Comment by asimlqt** [comment]
@kptLucek 

I have released a new version of the api (3.0) which includes some fairly big changes, I have also added a few dedicated exceptions.

There are conflicts with this PR and I'm guessing there will be quite a few so unfortunately I'm going to decline this PR. I hope the new version accomplishes what you did with this PR. Feel free to check it out and create a new PR if you still think it's lacking important features.

The reason I left this open for so long was that the changes were too big to merge into a minor update and warranted a major version update.

Thanks

**Pull request closed without merging**
